name: swg_pytorch_toy
channels:
- defaults
- conda-forge

dependencies:
  - python==3.11
  - pip==24.0
  - conda-build
  - pip:
    - torch==2.3.1
    - numpy==1.26.4 
    - tqdm == 4.66.6
    - scikit-learn
    - scipy>=1.4.1
    - wandb==0.17.3
    - einops==0.8.0
    - scipy>=1.4.1
    - h5py==3.11.0
    - imageio==2.34.2
    - imageio[ffmpeg]
    - matplotlib == 3.9.2
    - hydra-core == 1.3.2
    - pandas