env: "AntMaze"
policy: "umaze"
dataset_group: "D4RL"
dataset_entry: ${datasets.dataset_group}/${datasets.env}/${datasets.env}_${datasets.policy}-v0
env_entry: 'antmaze-umaze-v0'
critic_hyperparam: 0.9
dropout_rate: 0.0