env: "Adroit"
policy: "pen_cloned"
dataset_group: "D4RL"
dataset_entry: ${datasets.dataset_group}/${datasets.env}/${datasets.env}_${datasets.policy}-v0
env_entry: 'pen-cloned-v0'
critic_hyperparam: 0.7
dropout_rate: 0.1