env: "Walker2d"
policy: "medium_replay"
dataset_group: "D4RL"
dataset_entry: ${datasets.dataset_group}/${datasets.env}/${datasets.env}_${datasets.policy}-v2
env_entry: 'walker2d-medium-replay-v2'
critic_hyperparam: 0.7
dropout_rate: 0.1